// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/login","layout":false,"id":"1"},"2":{"path":"/","name":"dashboard","parentId":"@@/global-layout","id":"2"},"3":{"path":"/dashboard","redirect":"/","hideInMenu":true,"parentId":"@@/global-layout","id":"3"},"4":{"path":"/predict","name":"predict","parentId":"@@/global-layout","id":"4"},"5":{"path":"/battle","name":"battle","parentId":"@@/global-layout","id":"5"},"6":{"path":"/community","name":"community","parentId":"@@/global-layout","id":"6"},"7":{"path":"/comments","name":"comments","parentId":"@@/global-layout","id":"7"},"8":{"path":"/nodes","name":"nodes","parentId":"@@/global-layout","id":"8"},"9":{"path":"/risk","name":"risk","parentId":"@@/global-layout","id":"9"},"10":{"path":"/audit","name":"audit","parentId":"@@/global-layout","id":"10"},"11":{"path":"/rules","name":"rules","parentId":"@@/global-layout","id":"11"},"12":{"path":"/403","layout":false,"id":"12"},"13":{"path":"*","layout":false,"id":"13"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__Login__index" */'@/pages/Login/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Dashboard__index" */'@/pages/Dashboard/index.tsx')),
'3': React.lazy(() => import('./EmptyRoute')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Predict__index" */'@/pages/Predict/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Battle__index" */'@/pages/Battle/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__Community__index" */'@/pages/Community/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__Comments__index" */'@/pages/Comments/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__Nodes__index" */'@/pages/Nodes/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__Risk__index" */'@/pages/Risk/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__Audit__index" */'@/pages/Audit/index.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__Rules__index" */'@/pages/Rules/index.tsx')),
'12': React.lazy(() => import(/* webpackChunkName: "p__403__index" */'@/pages/403/index.tsx')),
'13': React.lazy(() => import(/* webpackChunkName: "p__404__index" */'@/pages/404/index.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'/Users/macbookpro/Documents/PolyMarket/forum/turtle-admin/src/layouts/index.tsx')),
},
  };
}
