export {
  useRequestAuditTopic,
  useRequestComments,
  useRequestDeleteComment,
  useRequestDeleteTopic,
  useRequestForbiddenUser,
  useRequestFundRecords,
  useRequestGrantAdmin,
  useRequestMintCoins,
  useRequestOperationLogs,
  useRequestPenaltyRules,
  useRequestRevokeAdmin,
  useRequestToggleTopicRecommend,
  useRequestToggleTopicSticky,
  useRequestTopicBy,
  useRequestTopics,
  useRequestUndeleteTopic,
  useRequestUpdateUserReport,
  useRequestUserReportBy,
  useRequestUserReports,
  useRequestUsers,
} from '@/hooks/useAdminRequest';
