// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_2 from '/Users/wangheng/Documents/PolyMarket/forum/turtle-admin/src/.umi/plugin-initialState/@@initialState';
import model_1 from '/Users/wangheng/Documents/PolyMarket/forum/turtle-admin/src/models/useAuthModel';

export const models = {
model_2: { namespace: '@@initialState', model: model_2 },
model_1: { namespace: 'useAuthModel', model: model_1 },
} as const
